import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage();
await p.setViewportSize({ width: 1440, height: 900 });
await p.goto('http://localhost:5173', { waitUntil: 'networkidle', timeout: 20000 });
await p.screenshot({ path: 'logo-nav.png' });
const footerTop = await p.evaluate(() => document.querySelector('footer')?.getBoundingClientRect().top + window.scrollY ?? 0);
await p.evaluate((y) => window.scrollTo(0, y), footerTop);
await p.waitForTimeout(500);
await p.screenshot({ path: 'logo-footer.png' });
await b.close();
