import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage();
await p.setViewportSize({ width: 1440, height: 900 });
await p.goto('http://localhost:5173/admin', { waitUntil: 'networkidle', timeout: 20000 });
await p.fill('input[type="text"]', 'admin');
await p.fill('input[type="password"]', 'koition2026');
await p.click('button[type="submit"]');
await p.waitForTimeout(1500);
await p.screenshot({ path: 'admin-dash.png' });
console.log('URL:', p.url());
await b.close();
